

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: azhar113
      MYSQL_DATABASE: Model_Logger
      MYSQL_USER: user
      MYSQL_PASSWORD: azhar113
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql  
      
  ml_app:
    image: my_ml_image
    container_name: ml_app
    ports:
      - "5000:5000"
    depends_on:
      - db  
    environment:
      Env FLASK_APP: ML_application.py 
      Env FLASK_ENV: development

volumes:
  db_data: 

